app = "kuralis"
primary_region = "mia"
console_command = "/rails/bin/rails console"

[build]

[deploy]
  release_command = "./bin/rails db:prepare"

[[services]]
  processes = ["app"]
  internal_port = 8080
  force_https = true
  auto_start_machines = true
  auto_stop_machines = "stop"
  min_machines_running = 1  # <-- keep one app machine running!

  [[services.ports]]
    handlers = ["http"]
    port = 80

  [[services.ports]]
    handlers = ["tls", "http"]
    port = 443

[processes]
  app = "./bin/rails server -b 0.0.0.0 -p 8080"
  worker = "bundle exec sidekiq"

[[vm]]
  processes = ["app"]
  memory = "1gb"
  cpu_kind = "shared"
  cpus = 1

[[vm]]
  processes = ["worker"]
  memory = "1gb"
  cpu_kind = "shared"
  cpus = 1


