# fly.toml app configuration file generated for kuralis on 2025-04-03T17:49:44Z
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'kuralis'
primary_region = 'mia'
console_command = '/rails/bin/rails console'

[build]

[[services]]
  internal_port = 8080
  protocol = "tcp
  auto_stop_machines = 'stop'
  auto_start_machines = true
  min_machines_running = 0

[[services.ports]]
  handlers = ["http"]
  force_https = true
  port = 80

[[vm]]
  memory = '1gb'
  cpu_kind = 'shared'
  cpus = 1
  memory_mb = 1024

[deploy]
release_command = "./bin/rails db:prepare"

[[processes]]
  name = "app"
  cmd = ["./bin/rails", "server", "-b", "0.0.0.0", "-p", "8080"]

[[processes]]
  name = "worker"
  cmd = ["bundle", "exec", "sidekiq"]