:queues:
  - default
  - mailers
  - active_storage_analysis
  - active_storage_purge
  - images

:scheduler:
  :schedule:
    sync_shopify_orders:
      cron: '*/2 * * * *'   # Every 2 minutes
      class: Shopify::SyncOrdersJob
      queue: default
      description: "Sync Shopify orders every 2 minutes"

    sync_ebay_orders:
      cron: '*/2 * * * *'   # Every 2 minutes
      class: Ebay::SyncOrdersJob
      queue: default
      description: "Sync eBay orders every 2 minutes" 